/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum JsRdfFormat {
  Turtle = 'Turtle',
  NTriples = 'NTriples',
  NQuads = 'NQuads',
  TriG = 'TriG',
  RdfXml = 'RdfXml',
  JsonLd = 'JsonLd',
  N3 = 'N3'
}
export const enum JsShaclFormat {
  Turtle = 'Turtle',
  NTriples = 'NTriples',
  NQuads = 'NQuads',
  TriG = 'TriG',
  RdfXml = 'RdfXml',
  JsonLd = 'JsonLd',
  N3 = 'N3'
}
export const enum JsShExFormat {
  ShExC = 'ShExC',
  ShExJ = 'ShExJ',
  Turtle = 'Turtle'
}
export const enum JsShapeMapFormat {
  Compact = 'Compact',
  Json = 'Json'
}
export const enum JsReaderMode {
  Lax = 'Lax',
  Strict = 'Strict'
}
export const enum JsShaclValidationMode {
  Native = 'Native',
  Sparql = 'Sparql'
}
export const enum JsShaclValidationSortMode {
  Severity = 'Severity',
  Node = 'Node',
  Component = 'Component',
  Value = 'Value',
  Path = 'Path',
  SourceShape = 'SourceShape',
  Details = 'Details'
}
export const enum JsResultShaclValidationFormat {
  Details = 'Details',
  Turtle = 'Turtle',
  NTriples = 'NTriples',
  RdfXml = 'RdfXml',
  TriG = 'TriG',
  N3 = 'N3',
  NQuads = 'NQuads',
  Minimal = 'Minimal',
  Compact = 'Compact',
  Json = 'Json',
  Csv = 'Csv'
}
export const enum JsResultShexValidationFormat {
  Details = 'Details',
  Turtle = 'Turtle',
  NTriples = 'NTriples',
  RdfXml = 'RdfXml',
  TriG = 'TriG',
  N3 = 'N3',
  NQuads = 'NQuads',
  Compact = 'Compact',
  Json = 'Json',
  Csv = 'Csv'
}
export const enum JsShexValidationSortMode {
  Node = 'Node',
  Shape = 'Shape',
  Status = 'Status',
  Details = 'Details'
}
export const enum JsResultDataFormat {
  Turtle = 'Turtle',
  NTriples = 'NTriples',
  NQuads = 'NQuads',
  JsonLd = 'JsonLd',
  RdfXml = 'RdfXml',
  TriG = 'TriG',
  N3 = 'N3',
  Compact = 'Compact',
  Json = 'Json'
}
export type JsRudofConfig = RudofConfig
/**
 * Configuration for a Rudof instance.
 *
 * Can be created with defaults or loaded from a TOML config file.
 */
export declare class RudofConfig {
  /** Creates a new `RudofConfig` with default settings. */
  constructor()
  /**
   * Loads a `RudofConfig` from a TOML file path.
   *
   * @param path - Absolute or relative path to the config file.
   */
  static fromPath(path: string): JsRudofConfig
}
export type JsRudof = Rudof
/**
 * The central Rudof context. Holds all loaded state: data, schemas, and validation results.
 *
 * All methods are synchronous. Operations that query SPARQL endpoints will block
 * the calling thread — offload with `node:worker_threads` or a thread pool.
 */
export declare class Rudof {
  /** Creates a new `Rudof` instance with the given configuration. */
  constructor(config: RudofConfig)
  resetAll(): void
  resetData(): void
  resetShacl(): void
  resetShex(): void
  resetShapemap(): void
  resetQuery(): void
  /**
   * Loads RDF data from a string, file path, URL, or SPARQL endpoint.
   * When `endpoint` is provided the `input` parameter is ignored.
   */
  readData(input?: string | undefined | null, format?: JsRdfFormat | undefined | null, base?: string | undefined | null, readerMode?: JsReaderMode | undefined | null, merge?: boolean | undefined | null, endpoint?: string | undefined | null): void
  /** Serializes the currently loaded RDF data to a string. */
  serializeData(format?: JsResultDataFormat | undefined | null): string
  /**
   * Loads SHACL shapes from a string, file path, or URL.
   * If `input` is omitted, shapes are extracted from the currently loaded data graph.
   */
  readShacl(input?: string | undefined | null, format?: JsShaclFormat | undefined | null, base?: string | undefined | null, readerMode?: JsReaderMode | undefined | null): void
  /** Serializes the currently loaded SHACL shapes to a string. */
  serializeShacl(format?: JsShaclFormat | undefined | null): string
  /**
   * Validates the loaded RDF data against the loaded SHACL shapes.
   * Call `readData` and `readShacl` first.
   */
  validateShacl(mode?: JsShaclValidationMode | undefined | null): void
  /**
   * Serializes the results of the last SHACL validation to a string.
   * Call `validateShacl` first.
   */
  serializeShaclValidationResults(format?: JsResultShaclValidationFormat | undefined | null, sortMode?: JsShaclValidationSortMode | undefined | null): string
  /** Loads a ShEx schema from a string, file path, or URL. */
  readShex(input: string, format?: JsShExFormat | undefined | null, base?: string | undefined | null, readerMode?: JsReaderMode | undefined | null): void
  /** Serializes the currently loaded ShEx schema to a string. */
  serializeShex(format?: JsShExFormat | undefined | null): string
  /**
   * Validates the loaded RDF data against the loaded ShEx schema using the loaded ShapeMap.
   * Call `readData`, `readShex`, and `readShapemap` first.
   */
  validateShex(): void
  /** Serializes the results of the last ShEx validation to a string. */
  serializeShexValidationResults(format?: JsResultShexValidationFormat | undefined | null, sortMode?: JsShexValidationSortMode | undefined | null): string
  /** Loads a ShapeMap from a string, file path, or URL. */
  readShapemap(input: string, format?: JsShapeMapFormat | undefined | null, baseNodes?: string | undefined | null, baseShapes?: string | undefined | null): void
  /** Serializes the currently loaded ShapeMap to a string. */
  serializeShapemap(format?: JsShapeMapFormat | undefined | null): string
  /** Loads a SPARQL query from a string, file path, or URL. */
  readQuery(input: string): void
  /** Executes the loaded SPARQL query against the loaded data. */
  runQuery(): void
  /** Serializes the results of the last executed SPARQL query to a string. */
  serializeQueryResults(): string
  /**
   * Lists known SPARQL endpoints from the current configuration.
   * Returns an array of `[name, url]` pairs.
   */
  listEndpoints(): Array<Array<string>>
  /** Returns a formatted neighbourhood view of a node in the RDF graph. */
  nodeInfo(nodeSelector: string, showColors?: boolean | undefined | null, depth?: number | undefined | null): string
}
